### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by bzimmer** [bzimmer/ma#89]
Ingesting a large number of files:

```fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0x14000167718?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/sema.go:62 +0x2c
sync.(*WaitGroup).Wait(0x1400010eb48)
	/opt/hostedtoolcache/go/1.20.4/x64/src/sync/waitgroup.go:116 +0x78
golang.org/x/sync/errgroup.(*Group).Wait(0x1400010eb40)
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:53 +0x2c
github.com/bzimmer/ma.(*entangler).cp(0x140000345a0, {0x1007fbe98, 0x140000280b0}, {0x140000712e0, 0x1, 0x2}, {0x16faf356d, 0x18})
	/home/runner/work/ma/ma/cp.go:111 +0x1a8
github.com/bzimmer/ma.cp(0x1400010e900)
	/home/runner/work/ma/ma/cp.go:257 +0x344
github.com/urfave/cli/v2.(*Command).Run(0x140001a6000, 0x1400010e900, {0x14000034550, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:274 +0x75c
github.com/urfave/cli/v2.(*Command).Run(0x140001a82c0, 0x1400010e600, {0x1400001e1e0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:267 +0x97c
github.com/urfave/cli/v2.(*App).RunContext(0x140001aa000, {0x1007fbe98?, 0x140000280b0}, {0x1400001e1e0, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:332 +0x604
main.main()
	/home/runner/work/ma/ma/cmd/ma/main.go:194 +0x1188

goroutine 6 [select]:
github.com/bzimmer/ma.(*entangler).cp.func1()
	/home/runner/work/ma/ma/cp.go:99 +0x340
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa0
```

**Comment by bzimmer** [comment]
Removed `cp` functionality
